### ISSUE TITLE
Separare implementazione e test

### ISSUE THREAD

**Issue by paolobrasolin** [tetrapharmakon/multinomiala#2]
Il codice inizia ad essere corposo ed è tipico separare implementazione e test in file distinti.

Puoi tenere l'implementazione in `multinomiala.py` e spostare i test in `multinomiala_test.py` avendo cura di importare il primo nel secondo usando `from multinomiala import *`. 

**NOTA**: l'asterisco ti permettere di accedere direttamente a ciò che importi da `multinomiala`; `import multinomiala` esporrebbe `multinomiala.Monomial` invece di `Monomial`.

**NOTA**: la corrispondenza `*.py` -> `*_test.py` è canonica.

**Comment by tetrapharmakon** [comment]
Fatto.

**Comment by paolobrasolin** [comment]
LPT: è possibile legare un commit ad una issue citandola nel commento di commit con il suo id (e.g. `#2` per questa issue). Questo ti permette di sapere su cosa stavi lavorando dando contesto ad un commit. Inoltre su GitHub quegli hash vengono sostituiti da dei link molto pratici.

**Comment by paolobrasolin** [comment]
Considera le righe che seguono https://github.com/tetrapharmakon/multinomiala/blob/6102d7edb2c5008292561fdd3a3f2195f06c8a8e/multinomiala.py#L69

Quei monomi sono gergalmente delle `fixtures` che servono _solo_ a fare funzionare i test.
Se li tieni separati dai test, rendi questi ultimi difficili da capire. Se li tieni assieme all'implementazione del modulo, ti ritroverai delle variabili potenzialmente fastidiose ad inquinare ogni progetto in cui importerai `multinomiala`. Not ideal.

**Comment by tetrapharmakon** [comment]
Corretto
