### ISSUE TITLE
Correggere uso dell'underscore nei nomi

### ISSUE THREAD

**Issue by paolobrasolin** [tetrapharmakon/multinomiala#3]
Ho commesso un'imprecisione.

I metodi privati (i.e. ad uso interno di una classe) hanno come prefisso `_` (singolo) e non `__` (doppio).
Funziona comunque, ma l'intenzione comunicata è differente: riallineiamoci alla convenzione.
Se sei curioso ecco [ulteriori informazioni](https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc).

**Comment by tetrapharmakon** [comment]
Mi sembra di capire che comunque l'overload degli operatori (somma, prodotto e cazzimme) usi i doppi underscore. Ovvero si debba cambiare
```
def __elevate(self):
    f = lambda (x,y):self._caret(x,y)
    straighten = sorted(zip(self.vees,self.exps))
    return ''.join(map(f,self._reduce(straighten)))
```
in 

```
def _elevate(self):
    f = lambda (x,y):self._caret(x,y)
    straighten = sorted(zip(self.vees,self.exps))
    return ''.join(map(f,self._reduce(straighten)))
```
ma non si debba cambiare
```
def __len__(self):
  return len(self.vees)
```

**Comment by paolobrasolin** [comment]
Esatto. `__nome__` (prefisso e suffisso con doppi underscore) denota che il metodo ha un ruolo magico ed eccezionale, quindi è riservato solo a cose molto specifiche. Ad esempio, i metodi che vengono usati per implementare degli operatori (`__lt__` -> `<`) o metodi di interfacce standard (`__len__` -> `len`). O anche il metodo che viene chiamato internamente per inizializzare una nuova istanza di una classe (`Monomial.__init__` -> `Monomial(...)` ).

**Comment by tetrapharmakon** [comment]
Ora è corretto
